[workspace]
resolver = "2"
members = [
	"chirpstack",
	"chirpstack-integration",
	"lrwn",
	"lrwn-filters",
	"backend",
	"api/rust",
]

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1

[patch.crates-io]
# Remove if diesel-async > 0.4.1
diesel-async = { git = "https://github.com/weiznich/diesel_async.git", rev = "b8b01cc6a3a999171c502645eb8965ed0ab60a1f" }
